services:
  - type: web
    name: experimento-chatbot
    env: python
    buildCommand: pip install -r requirements.txt && python -m spacy download es_core_news_sm && python -m spacy download en_core_web_sm && python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords'); nltk.download('averaged_perceptron_tagger')"
    startCommand: uvicorn main_improved:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: HF_API_TOKEN
        sync: false
      - key: FRONTEND_URL
        value: https://experimento-frontend.onrender.com 